version: "3"

services:
  web:
    build: .
    ports:
    - "5000:5000"
    links:
      - db
    volumes:
    - ".:/web"
  db:
    image: mongo:4.2.2

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - "redis:/data"
  celery:
    build: .
    command: celery -A web.tasks worker --loglevel=info
    volumes:
    - ".:/web"
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]
    ports:
      - 8888:8888

volumes:
  redis: {}